# Generated by Django 3.1.4 on 2022-01-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220123_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.product'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('product', 'prod_size')},
        ),
    ]
